version: '3.7'
services:
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    hostname: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=single-twitter-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - 5601:5601
    depends_on:
      - elastic-1
    environment:
      ELASTICSEARCH_HOSTS: http://elastic-1:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    command: logstash -f /etc/logstash/conf.d/logback.conf
    ports:
      - 9600:9600
    depends_on:
      - elastic-1
    volumes:
      - ./config/logback.conf:/etc/logstash/conf.d/logback.conf
      - ./docker-logs/logstash:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xms512m"
      CLUSTER_NAME: single-twitter-cluster
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elastic-1:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

volumes:
  data01:
    driver: local