server:
  port: 8761
eureka:
  client:
#    register-with-eureka: true
    register-with-eureka: false
#    fetch-registry: true
    fetch-registry: false
  instance:
    appname: service-registry-cluster

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: singleserver